### ISSUE TITLE
Uncaught SyntaxError: ~/Documents\Arduino\PlatformIO\mqtt-ir-transceiver-master\.gcc-flags.json: ...

### ISSUE THREAD

**Issue by 6s1gm4** [hebaishi/linter-gcc#112]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.0 ia32
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [linter-gcc](https://github.com/hebaishi/linter-gcc) package 0.7.1

### Stack Trace

Uncaught SyntaxError: C:\Users\win\Documents\Arduino\PlatformIO\mqtt-ir-transceiver-master\.gcc-flags.json: Unexpected token  in JSON at position 0

```
At C:\Users\win\AppData\Local\atom\app-1.14.0\resources\app.asar\src\pane.js:1045

SyntaxError: C:\Users\win\Documents\Arduino\PlatformIO\mqtt-ir-transceiver-master\.gcc-flags.json: Unexpected token  in JSON at position 0
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:573:27)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.settings (/packages/linter-gcc/lib/config.js:49:25)
    at Object.buildCommand (/packages/linter-gcc/lib/utility.js:127:23)
    at Object.lint (/packages/linter-gcc/lib/main.js:110:36)
    at lintOnSave (/packages/linter-gcc/lib/main.js:191:22)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1082:27)
    at TextBuffer.module.exports.TextBuffer.save (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1049:19)
    at TextEditor.module.exports.TextEditor.save (/app.asar/src/text-editor.js:890:26)
    at Pane.module.exports.Pane.saveItem (/app.asar/src/pane.js:753:18)
    at Pane.saveItem (/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/app.asar/src/pane.js:736:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/app.asar/src/workspace.js:693:35)
    at /app.asar/src/register-default-commands.js:225:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
  6x -3:08.9.0 core:backspace (input.hidden-input)
     -2:56.8.0 core:copy (input.hidden-input)
     -2:45.2.0 core:cut (input.hidden-input)
     -2:43.5.0 core:delete (input.hidden-input)
     -2:38 core:paste (input.hidden-input)
     -2:34.9.0 snippets:next-tab-stop (input.hidden-input)
     -2:34.9.0 snippets:expand (input.hidden-input)
     -2:34.9.0 editor:indent (input.hidden-input)
     -2:33.9.0 snippets:next-tab-stop (input.hidden-input)
     -2:33.9.0 snippets:expand (input.hidden-input)
     -2:33.9.0 editor:indent (input.hidden-input)
     -2:30.8.0 core:save (input.hidden-input)
  5x -1:34.9.0 core:undo (input.hidden-input)
     -0:10.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-clang 0.10.0 
build 0.67.0 
busy 0.7.0 
file-icons 2.0.14 
language-ini 1.17.0 
linter 1.11.21 
linter-gcc 0.7.1 
minimap 4.26.8 
platformio-ide 1.7.2 
platformio-ide-terminal 2.2.2 
tool-bar 1.0.1 
```

**Comment by hebaishi** [comment]
The error suggests your json file is invalid. Could you paste it here?
