### ISSUE TITLE
[solved] Failed to activate the linter-gcc package

### ISSUE THREAD

**Issue by Dynamic-Gravity** [hebaishi/linter-gcc#123]
The error I received was:

>Arguments to CompositeDisposable.add must have a .dispose() method

My GCC version:
```
[luke@Venus 310-intermediate]$ gcc --version
gcc (GCC) 6.3.1 20170306
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
What I tried:
```
[luke@Venus 310-intermediate]$ apm uninstall linter
Uninstalling linter ✓
(node:13228) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[luke@Venus 310-intermediate]$ apm install linter
(node:13234) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Installing linter to /home/luke/.atom/packages ✓
```
```
[luke@Venus 310-intermediate]$ apm uninstall linter-gcc
Uninstalling linter-gcc ✓
(node:13583) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[luke@Venus 310-intermediate]$ apm install linter-gcc
(node:13589) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Installing linter-gcc to /home/luke/.atom/packages ✓
```

Here is the stack trace from the error.

>TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/usr/lib/atom/node_modules/event-kit/lib/composite-disposable.js:74:13)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/usr/lib/atom/node_modules/event-kit/lib/composite-disposable.js:43:11)
    at Object.consumeLinter (/home/luke/.atom/packages/linter-gcc/lib/main.js:211:10)
    at Provider.module.exports.Provider.provide (/usr/lib/atom/node_modules/service-hub/lib/provider.js:34:52)
    at ServiceHub.module.exports.ServiceHub.consume (/usr/lib/atom/node_modules/service-hub/lib/service-hub.js:50:18)
    at Package.module.exports.Package.activateServices (/usr/lib/atom/src/package.js:404:75)
    at Package.module.exports.Package.activateNow (/usr/lib/atom/src/package.js:221:16)
    at /usr/lib/atom/src/package.js:190:32
    at Package.module.exports.Package.measure (/usr/lib/atom/src/package.js:96:15)
    at /usr/lib/atom/src/package.js:183:26
    at Package.module.exports.Package.activate (/usr/lib/atom/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/lib/atom/src/package-manager.js:542:34)
    at /usr/lib/atom/src/package-manager.js:523:29
    at Config.module.exports.Config.transactAsync (/usr/lib/atom/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/lib/atom/src/package-manager.js:518:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/lib/atom/src/package-manager.js:500:46)
    at /usr/lib/atom/src/atom-environment.js:826:28

What would be the next step if uninstalling/reinstalling the linter and linter-gcc packages doesn't work?

EDIT: What it looks like with other people's comments, the lasted update broke something.

**Comment by mpcmarques** [comment]
same here

**Comment by Dynamic-Gravity** [comment]
@mpcmarques Did you just do an update too?

**Comment by Superdanby** [comment]
+1
after the update.

**Comment by MacWyznawca** [comment]
+1
I too :-( 
macOS 10.12.5 Beta (16F54b)

**Comment by softsmyth** [comment]
+1
fresh install of PlatformIO

**Comment by basedjux** [comment]
Get the same stack trace as @Dynamic-Gravity 
Running macOS Sierra 10.12.4
Attempted uninstall and reinstall of both linter and linter-gcc through APM but didn't work.

**Comment by arthur29498** [comment]
+1
After the update all the same
On arch

**Comment by Dynamic-Gravity** [comment]
@arthur29498 I'm on arch as well.

**Comment by phrockell** [comment]
Same on Linux Mint 18, with a cleanly installed Atom IDE.

**Comment by Arcanemagus** [comment]
Can any of you point to a recent change that would have triggered this?

Did the latest `linter` update 4 hours ago break this? You can force install the older version to check with `apm install linter@2.1.2`.

**Comment by Dynamic-Gravity** [comment]
@Arcanemagus, yes I believe that is what broke this. As I was using Atom this morning, then noticed an update with that package, after which this error occurred.

**Comment by steelbrain** [comment]
Sorry everyone, you can expect a bugfix release in a few minutes, we (base linter team) messed up 🙇 https://github.com/steelbrain/linter/pull/1434

**Comment by Dynamic-Gravity** [comment]
@steelbrain thanks for the update!

**Comment by steelbrain** [comment]
Sorry for the trouble everyone, Linter v2.1.4 is out with the fix

**Comment by Dynamic-Gravity** [comment]
@steelbrain thank you, linter-gcc is working again.

**Comment by basedjux** [comment]
Awesome! Thanks @steelbrain and co. Will re-download now.

**Comment by softsmyth** [comment]
looks good now... thanks!
