### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir ''

### ISSUE THREAD

**Issue by C0oo1D** [hebaishi/linter-gcc#130]
[Enter steps to reproduce:]

1. open atom, set GCC Include Paths: "/*" (try to search files in all project folder recursively)
2. open main.c (and proj structure from it)
3. ctrl+s

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Windows 10 Anniversary Edition (LTSB)
**Thrown From**: [linter-gcc](https://github.com/hebaishi/linter-gcc) package 0.7.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir ''

```
At C:\Users\C0oo1D\AppData\Local\atom\app-1.17.2\resources\app\src\pane.js:1095

Error: ENOENT: no such file or directory, scandir ''
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at Object.walkSync (/packages/linter-gcc/lib/utility.js:15:16)
    at /packages/linter-gcc/lib/utility.js:110:37
    at Array.forEach (native)
    at Object.splitStringTrim (/packages/linter-gcc/lib/utility.js:97:14)
    at Object.buildCommand (/packages/linter-gcc/lib/utility.js:197:42)
    at Object.lint (/packages/linter-gcc/lib/main.js:110:36)
    at lintOnSave (/packages/linter-gcc/lib/main.js:191:22)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at TextBuffer.module.exports.TextBuffer.saveAs (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/text-buffer/lib/text-buffer.js:1142:1)
    at TextBuffer.module.exports.TextBuffer.save (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/text-buffer/lib/text-buffer.js:1108:1)
    at TextEditor.module.exports.TextEditor.save (~/AppData/Local/atom/app-1.17.2/resources/app/src/text-editor.js:925:1)
    at Pane.module.exports.Pane.saveItem (~/AppData/Local/atom/app-1.17.2/resources/app/src/pane.js:780:1)
    at Pane.saveItem (~/AppData/Local/atom/app-1.17.2/resources/app/src/pane.js:3:1)
    at Pane.module.exports.Pane.saveActiveItem (~/AppData/Local/atom/app-1.17.2/resources/app/src/pane.js:763:1)
    at Workspace.saveActivePaneItem (~/AppData/Local/atom/app-1.17.2/resources/app/src/workspace.js:1498:1)
    at atom-workspace.core:save (~/AppData/Local/atom/app-1.17.2/resources/app/src/register-default-commands.js:236:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.2/resources/app/src/command-registry.js:265:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.17.2/resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.17.2/resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -0:16.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -0:10 intentions:highlight (input.hidden-input)
     -0:09.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-clang 0.11.3 
build 0.68.0 
busy 0.7.0 
busy-signal 1.4.1 
file-icons 2.1.7 
git-hide 1.0.0 
intentions 1.1.2 
language-ini 1.19.0 
linter 2.1.4 
linter-gcc 0.7.1 
linter-ui-default 1.6.0 
minimap 4.28.2 
tool-bar 1.1.0 
```

**Comment by C0oo1D** [comment]
when i put direct path `.\lib\CMSIS`, where not founded file are is, linter show 2-3 errors number, but not showed description. Then I manually opened Linter error list - they are empty!

**Comment by mbhakta15** [comment]
My linter was working fine for almost 4 months. This problem happened to me out of nowhere today. Whats up with this? Did you guys ever find the solution?
