### ISSUE TITLE
Uncaught TypeError: Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by Shiratsuyu** [hebaishi/linter-gcc#133]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0-beta3 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [linter-gcc](https://github.com/hebaishi/linter-gcc) package 0.7.1

### Stack Trace

Uncaught TypeError: Cannot read property 'file' of undefined

```
At /Users/Shiratsuyu/.atom/packages/linter-gcc/lib/utility.js:64

TypeError: Cannot read property 'file' of undefined
    at Object.getFileDir (/packages/linter-gcc/lib/utility.js:64:32)
    at /packages/linter-gcc/lib/utility.js:105:44
    at Array.forEach (native)
    at Object.splitStringTrim (/packages/linter-gcc/lib/utility.js:97:14)
    at Object.buildCommand (/packages/linter-gcc/lib/utility.js:197:42)
    at Object.lint (/packages/linter-gcc/lib/main.js:110:36)
    at /packages/linter-gcc/lib/main.js:180:26
```

### Commands

```
     -0:45.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
```

### Non-Core Packages

```
autocomplete-clang 0.11.3 
busy-signal 1.4.3 
dbg 1.6.1 
dbg-gdb 1.7.6 
file-icons 2.1.7 
gcc-make-run 0.2.9 
gloom 0.6.4 
intentions 1.1.2 
language-cpp14 0.6.2 
language-lua 0.9.11 
linter 2.2.0 
linter-gcc 0.7.1 
linter-lua 1.0.4 
linter-lua-findglobals 1.2.0 
linter-ui-default 1.6.1 
nord-atom-ui 0.11.0 
output-panel 0.3.2 
platformio-ide-terminal 2.5.1 
ramda-syntax 1.0.4 
simplified-chinese-menu 5.3.4 
vim-mode-plus 0.93.0 
vim-mode-plus-ex-mode 0.9.1 
```

**Comment by xansyu** [comment]
@hebaishi 
When I preview a **.cpp/.c/.h** file, this error will be thrown.

But if I don't change the default **GCC Include paths** or use the **.gcc-flags.json** without modifying the **"gccIncludePaths"**, this error won't be thrown.

I wonder why and how I can avoid this error.

Well, thanks anyway.
