### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir 'Dev/CDevs'

### ISSUE THREAD

**Issue by Unee0x** [hebaishi/linter-gcc#134]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [linter-gcc](https://github.com/hebaishi/linter-gcc) package 0.7.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir 'Dev/CDevs'

```
At fs.js:951

Error: ENOENT: no such file or directory, scandir 'Dev/CDevs'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at Object.walkSync (/packages/linter-gcc/lib/utility.js:15:16)
    at /packages/linter-gcc/lib/utility.js:110:37
    at Array.forEach (native)
    at Object.splitStringTrim (/packages/linter-gcc/lib/utility.js:97:14)
    at Object.buildCommand (/packages/linter-gcc/lib/utility.js:197:42)
    at Object.lint (/packages/linter-gcc/lib/main.js:110:36)
    at lintOnSave (/packages/linter-gcc/lib/main.js:191:22)
    at Function.module.exports.Emitter.simpleDispatch (/private/var/folders/pj/8fwfdlz131d1q5krvtyrcd_80000gn/T/AppTranslocation/EDAF3909-A8D8-46EC-81DD-BACE1929870D/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/private/var/folders/pj/8fwfdlz131d1q5krvtyrcd_80000gn/T/AppTranslocation/EDAF3909-A8D8-46EC-81DD-BACE1929870D/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.saveAs (/private/var/folders/pj/8fwfdlz131d1q5krvtyrcd_80000gn/T/AppTranslocation/EDAF3909-A8D8-46EC-81DD-BACE1929870D/d/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1142:33)
    at TextBuffer.module.exports.TextBuffer.save (/private/var/folders/pj/8fwfdlz131d1q5krvtyrcd_80000gn/T/AppTranslocation/EDAF3909-A8D8-46EC-81DD-BACE1929870D/d/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1108:25)
    at TextEditor.module.exports.TextEditor.save (/private/var/folders/pj/8fwfdlz131d1q5krvtyrcd_80000gn/T/AppTranslocation/EDAF3909-A8D8-46EC-81DD-BACE1929870D/d/Atom.app/Contents/Resources/app/src/text-editor.js:925:32)
    at compile (/packages/gpp-compiler/index.js:268:12)
    at compileFile (/packages/gpp-compiler/index.js:216:5)
    at /packages/gpp-compiler/index.js:23:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/private/var/folders/pj/8fwfdlz131d1q5krvtyrcd_80000gn/T/AppTranslocation/EDAF3909-A8D8-46EC-81DD-BACE1929870D/d/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /private/var/folders/pj/8fwfdlz131d1q5krvtyrcd_80000gn/T/AppTranslocation/EDAF3909-A8D8-46EC-81DD-BACE1929870D/d/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/private/var/folders/pj/8fwfdlz131d1q5krvtyrcd_80000gn/T/AppTranslocation/EDAF3909-A8D8-46EC-81DD-BACE1929870D/d/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/private/var/folders/pj/8fwfdlz131d1q5krvtyrcd_80000gn/T/AppTranslocation/EDAF3909-A8D8-46EC-81DD-BACE1929870D/d/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/pj/8fwfdlz131d1q5krvtyrcd_80000gn/T/AppTranslocation/EDAF3909-A8D8-46EC-81DD-BACE1929870D/d/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/private/var/folders/pj/8fwfdlz131d1q5krvtyrcd_80000gn/T/AppTranslocation/EDAF3909-A8D8-46EC-81DD-BACE1929870D/d/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -7:25.7.0 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -6:37.6.0 editor:newline (input.hidden-input)
  4x -6:31 core:backspace (input.hidden-input)
     -0:34.1.0 gpp-compiler:compile (input.hidden-input)
```

### Non-Core Packages

```
build-cocos 0.5.3 
busy-signal 1.4.3 
gpp-compiler 3.0.7 
intentions 1.1.2 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.6.1 
```

**Comment by MCorneliu** [comment]
i find a fix?
