### ISSUE TITLE
Failed to activate the linter-gcc package

### ISSUE THREAD

**Issue by xndxcsd** [hebaishi/linter-gcc#14]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Unknown Windows Version
**Thrown From**: [linter-gcc](https://github.com/hebaishi/linter-gcc) package, v0.5.0

### Stack Trace

Failed to activate the linter-gcc package

```
At Cannot find module 'atom-linter'

Error: Cannot find module 'atom-linter'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\csd\AppData\Local\atom\app-1.2.4\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.provideLinter (C:/Users/csd/.atom/packages/linter-gcc-0.5.0/lib/main.js:43:21)
    at Package.module.exports.Package.activateServices (C:\Users\csd\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:327:69)
    at Package.module.exports.Package.activateNow (C:\Users\csd\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:173:16)
    at C:\Users\csd\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:150:32
    at Package.module.exports.Package.measure (C:\Users\csd\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:92:15)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "disabledPackages": [
      "linter-gcc",
      "linter-gcc",
      "linter-gcc",
      "linter-gcc",
      "linter-gcc"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by hebaishi** [comment]
You need to install the base linter package, found [here](https://atom.io/packages/linter)

**Comment by hebaishi** [comment]
Please try re-installing linter-gcc. The base linter is now automatically installed if it's missing. Please update linter-gcc to use this new feature.

**Comment by xndxcsd** [comment]
The problem solved by your help. 
Thank you very much .
