### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir './commands'     at Object.readdirSync (fs.js:809:3)     at Object.<anonymous> (E:\games\Bot\index.js:8:25)     at Module._compile (internal/modules/cjs/loader.js:722:30)     at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)     at Module.load (internal/modules/cjs/loader.js:620:32)     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)     at Function.Module._load (internal/modules/cjs/loader.js:552:3)     at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)     at startup (internal/bootstrap/node.js:300:19)     at bootstrapNodeJSCore (internal/bootstrap/node.js:826:3)

### ISSUE THREAD

**Issue by Seleran** [hebaishi/linter-gcc#196]
## Checklist
* [ ] Check that you have the GNU C Compiler installed by typing ```gcc --version``` into a terminal.
* [ ] If you don't have the ```linter``` package installed, either update to the latest version of ```linter-gcc``` or install linter directly with ```apm install linter```.
* [ ] Ensure that you are using a valid grammar - either C/C++/C++14
* [ ] Ensure that you have read all the relevant information in the [wiki](https://github.com/hebaishi/linter-gcc/wiki), particularly the [Common Issues](https://github.com/hebaishi/linter-gcc/wiki/Common-Issues) page.

**Comment by Hex052** [comment]
This package does not seem to be maintained anymore. Try @tvincent056's fork, [linter-gcc2](https://atom.io/packages/linter-gcc2). See [comment](https://github.com/hebaishi/linter-gcc/pull/185#issuecomment-435928445) on #185
