### ISSUE TITLE
Uncaught TypeError: Cannot read property 'binary' of undefined

### ISSUE THREAD

**Issue by sakrebleu** [hebaishi/linter-gcc#29]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: ALI-PC
**Thrown From**: [linter-gcc](https://github.com/hebaishi/linter-gcc) package, v0.6.5

### Stack Trace

Uncaught TypeError: Cannot read property 'binary' of undefined

```
At C:\Users\Ali\AppData\Local\atom\app-1.5.3\resources\app.asar\src\pane.js:825

TypeError: Cannot read property 'binary' of undefined
    at Object.lint (C:/Users/Ali/.atom/packages/linter-gcc/lib/main.js:61:32)
    at lintOnSave (C:/Users/Ali/.atom/packages/linter-gcc/lib/main.js:107:22)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Ali\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Ali\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\Ali\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1067:27)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\Ali\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1037:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\Ali\AppData\Local\atom\app-1.5.3\resources\app.asar\src\text-editor.js:630:26)
    at Pane.module.exports.Pane.saveItem (C:\Users\Ali\AppData\Local\atom\app-1.5.3\resources\app.asar\src\pane.js:545:18)
    at Pane.module.exports.Pane.saveActiveItem (C:\Users\Ali\AppData\Local\atom\app-1.5.3\resources\app.asar\src\pane.js:528:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\Ali\AppData\Local\atom\app-1.5.3\resources\app.asar\src\workspace.js:649:35)
    at atom-workspace.commandRegistry.add.core:save (C:\Users\Ali\AppData\Local\atom\app-1.5.3\resources\app.asar\src\register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Ali\AppData\Local\atom\app-1.5.3\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Ali\AppData\Local\atom\app-1.5.3\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Ali\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Ali\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\Ali\AppData\Local\atom\app-1.5.3\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\Ali\AppData\Local\atom\app-1.5.3\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -9:54.9.0 core:save (div.package-detail.panels-item)
     -9:34.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -9:31.1.0 core:save (atom-text-editor.editor.is-focused)
     -8:58.7.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -8:57.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "minimap"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "linter-gcc": {
    "execPath": "MinGW/bin/gcc"
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.13
autoclose-html, v0.20.0
autocomplete-html-entities, v0.1.0
autocomplete-python, v1.6.1
color-picker, v2.1.1
linter, v1.11.3
linter-gcc, v0.6.5
terminal-plus, v0.14.5

# Dev
No dev packages
```

Can someone help me I installed Atom new and i dont know what i did wrong.

**Comment by Skosulor** [comment]
Hey, i just installed platformIO atom IDE and just got the same problem, Would be happy if you would share solution if you found one :)

**Comment by hebaishi** [comment]
The issue here was probably that gcc wasn't installed. Please read the [wiki](https://github.com/hebaishi/linter-gcc/wiki/Common-Issues) and follow the steps there.

**Comment by hebaishi** [comment]
Hello. Is it working for you now?

**Comment by Skosulor** [comment]
Im trying a reinstall right now, im on windows and having a few problems.
My goal is first to compile and run c++ files and second is to get linter
to work.

The wiki says something about gcc version 6.0, seems i have an much older
version, 2.91.57. Does cygwin install the latest?

Im using the gpp-compiler package to compile my c++ files but i get an
error that "start" could not be spawned and be added to path but i have no
clue what "start" is, g++ is in the path and working, i get a compiled file.

Thanks for the help!

**Comment by hebaishi** [comment]
You mis-read the wiki. The wiki says that versions 0.6.0 -> 0.6.5 of ```linter-gcc``` are missing a feature (the automatic installation of the base linter package), but I assume you have installed the latest version of ```linter-gcc``` which means you shouldn't have this problem. What you need to do is setup ```g++``` on cygwin so that ```g++``` is in your ```$PATH``` so that the command ```g++ --version``` works in the terminal.

**Comment by hebaishi** [comment]
Please see [this](http://cs.calvin.edu/curriculum/cs/112/resources/installingEclipse/cygwin/) guide on how to install gcc/g++ on Cygwin.

**Comment by Skosulor** [comment]
I've gotten that to work, g++ is in the path and i can use g++ in cmd

**Comment by hebaishi** [comment]
Ok. Now all your need to do is specify ```g++``` as your executable path in the ```linter-gcc``` configuration settings and it should just work.

**Comment by Skosulor** [comment]
Do i do that in the config.js file for linter-gcc? I Couldn't find anything about specifying path in the settings.

**Comment by hebaishi** [comment]
No. In atom, you click Packages > Settings View > Open. Then click Packages on the right hand panel, and type ```linter-gcc``` into the filter box. Click Settings it to get to the configuration settings.

**Comment by hebaishi** [comment]
It seems you are unfamiliar with atom. I suggest you read the Atom Flight Manual [here](https://atom.io/docs/latest/) to get more familiar with the interface.

**Comment by Skosulor** [comment]
Yes, i first found out about it a few days ago, thanks alot! :+1:

**Comment by hebaishi** [comment]
Is linter-gcc working for you?

**Comment by Skosulor** [comment]
No i get the error,

"linter-gcc: Executable not found"
"C:\MinGW\bin" not found

and

Uncaught TypeError: Cannot read property 'binary' of undefined
/C:/Users/Andreas/.atom/packages/linter-gcc/lib/main.js:72

**Comment by hebaishi** [comment]
The binary you have entered is still incorrect. You need to enter ```g++``` into the linter-gcc configuration settings page (in the GCC Executable Path), **NOT** ```C:\MinGW\bin```. The full path (I'm assuming it's ```C:\MinGW\bin\g++```) will not work because g++ needs to know where to find its header files. It has to be in your path for this whole thing to work.

**Comment by Skosulor** [comment]
Ah thank you, now i no longer get the error! But seems i forgot to install clang... Thanks alot for helping me and explaining in a way i understand :)

**Comment by hebaishi** [comment]
Clang is a different compiler from g++. Does linting C/C++ code work for you now?

**Comment by Skosulor** [comment]
Yeah it works now!

**Comment by quantumlaser** [comment]
@hebaishi Hello, I tried: C:\MinGW\bin\g++, but it still not work.

**Comment by heroics** [comment]
I'm also having this problem. I tried ` C:\MinGW\bin\g++.exe` and it still doesn't work.

**Comment by heyxiaosong** [comment]
thanks for the guidence! I’ve fixed it.

**Comment by HanKooR** [comment]
Sometimes this error occurs when storing/using/writing the same project from different OS-platforms to the same folder (e.g. on cloud ...)


> 
Uncaught TypeError: Cannot read property 'binary' of undefined
> 
At /usr/share/atom/resources/app.asar/src/pane.js:1002
> 
TypeError: Cannot read property 'binary' of undefined

If this is your issue, you need to re-init your project from the 'platformio' menu.

**Comment by SKKSaikia** [comment]
Sir, can you make a tutorial out to fix this error & post it in youtube ?

**Comment by HanKooR** [comment]
To whom was this replay/question directed?

**Comment by hebaishi** [comment]
To me, I believe. I'm writing a guide for windows users now.

**Comment by SKKSaikia** [comment]
Anyone who is willing to help.A tutorial from installing ,integrating gcc & compiling+running will be very helpful.

**Comment by SKKSaikia** [comment]
Sir, I am stuck up here - https://www.quora.com/How-do-I-integrate-GCC-with-Atom-to-compile-C++-code

Also I went to package>settings & under GCC path - gave g++ but nuthing works.Help from here is welcome.I am a beginner, so I might have made mistakes.please look in the description of quora.

**Comment by hebaishi** [comment]
You have done the right thing and added `g++` to your PATH. You just need to set your linter-gcc executable path to `g++.exe` and it should work.

**Comment by hebaishi** [comment]
You are using the wrong header files. `conio.h` is a C header, and in C++ to use `cin` and `cout`, you `#include <iostream>`.
Your code looks like C++ code, so delete the conio include, and change the iostream include to `#include <iostream>`.

Please read [this](http://www.learncpp.com/cpp-tutorial/19-header-files/) article on header files.

**Comment by SKKSaikia** [comment]
Ok,Thank You Sir.
I got to update myself,I was trying to code what I learned in school days in Turbo C++.

Works Now Thanks.
![eee](https://cloud.githubusercontent.com/assets/19411553/16409863/3be6fc92-3d3d-11e6-80b4-c73beb314de6.JPG)

**Comment by dcharua** [comment]
Hi,i was getting this error beacuse i used bash to install gcc, now i found the file in this directory C:\Users\Daniel\AppData\Local\lxss\rootfs\usr\bin\g++    
![image](https://cloud.githubusercontent.com/assets/20179220/17876470/0bda9142-68a0-11e6-87c8-401ea00e87ea.png)

Im not gettign error #29 anymore but its still not linting
![image](https://cloud.githubusercontent.com/assets/20179220/17876486/364c0fdc-68a0-11e6-9c49-5a51f6889e30.png)

**Comment by AlgorithmEnigma** [comment]
@hebaishi I have gotten the g++ compiler through minGW and can compile it from the terminal, so its added to my PATH and I have my GCC Executable Path set to "g++.exe" but it still won't work?



![screenshot 1](https://cloud.githubusercontent.com/assets/22643101/19217565/75cc41c8-8dac-11e6-8b14-578cf3dabc22.png)

**Comment by hebaishi** [comment]
The wiki contains a guide for windows users. Please follow the instructions in the guide.

**Comment by AlgorithmEnigma** [comment]
Yes, I've done all of that and it still wont work.

**Comment by shaiksuraz** [comment]
C:\MinGW\bin\g++.exe

Settings   ->   Packages   ->    linter-gcc   ->    Settings   ->    GCC Executable Path  ->   C:\MinGW\bin\g++.exe

**Comment by mildful** [comment]
Maybe a stupid question : 
I am setting up an environment to code in C / C++ and I am using linux bash in windows 10. I work with Atom and platformio-ide-terminal which open my bash terminal. In this terminal, I've installed build-essentials so I am able to run `gcc` on my linux (via windows).

But how can I tell lintner-gcc to use this gcc ?

I am replying to this issue because the error is the same. Sorry if this is the wrong place.

**Comment by jalexandre0** [comment]
Just a tip: 

If you had g++ installed and added to path and still having problems with linter-gcc (i had a weird issue on save), just go to Platform.io menu and update the project folder. 

This solved the save issue for me.

**Comment by sn34ks** [comment]
I realize this is a very vague comment, however I wanted to post in case someone having this issue is using Linter-GCC with Platform IO/Atom.  On a fresh PIO/Atom install I continually had this issue until I ran 'BUILD' on a project for the first time.  Atom/PIO downloaded some additional files and when built Linter-GCC ran fine thereafter.

**Comment by bdemirel** [comment]
I had the same problem even though I had gcc in $PATH (it was working from cmd) and executable path from settings was "C:\MinGW\bin\g++" as written on the Wiki. However, trying the suggestion here and setting it to "C:\MinGW\bin\g++.exe" solved my problem. I think you should update your Wiki accordingly as it suggests the complete opposite right now.

**Comment by ingenierojaveriano** [comment]
i did found a solution and it's rewrite the GCC Executable Path, in my case for example it will be C:\MinGW\bin/gcc.exe, So it really fixed my problem.
![image](https://cloud.githubusercontent.com/assets/17032354/26524896/a1f3c060-4345-11e7-874f-c9accd162d21.png)

**Comment by hck94829** [comment]
Mine did not work on mac as well... and i've installed my gcc using home-brew at /usr/local/Cellar/gcc/
