### ISSUE TITLE
Custom compiler in .gcc-flags.json

### ISSUE THREAD

**Issue by edjubuh** [hebaishi/linter-gcc#38]
[Enter steps to reproduce below:]

1. Modify .gcc-flags.json in project root directory to:
```json
{
  "execPath": "arm-none-eabi-g++",
  "gccIncludePaths": "./include"
}
```

Changing the execPath globally via the Settings pane works fine. If I change `arm-none-eabi-gcc` to just `gcc`, I get "gcc" not found as expected since gcc is not on my PATH but arm-none-eabi-gcc is

**Atom Version**: 1.5.4
**System**: Microsoft Windows 10 Education
**Thrown From**: [linter-gcc](https://github.com/hebaishi/linter-gcc) package, v0.6.8

### Stack Trace

Uncaught TypeError: Cannot read property 'trim' of undefined

```
At C:\Users\Elliot\.atom\packages\linter-gcc\lib\utility.js:45

TypeError: Cannot read property 'trim' of undefined
    at Object.module.exports.splitStringTrim (C:\Users\Elliot\.atom\packages\linter-gcc\lib\utility.js:45:14)
    at Object.module.exports.buildCommand (C:\Users\Elliot\.atom\packages\linter-gcc\lib\utility.js:100:37)
    at Object.lint (C:/Users/Elliot/.atom/packages/linter-gcc/lib/main.js:74:36)
    at lintOnTheFly (C:/Users/Elliot/.atom/packages/linter-gcc/lib/main.js:124:22)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Elliot\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Elliot\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:\Users\Elliot\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1321:25
```

### Commands

```
     -1:50.9.0 core:save (atom-text-editor.editor.is-focused)
  3x -1:47.7.0 core:backspace (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:27.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:25 core:backspace (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:21.3.0 autocomplete-plus:cancel (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:19.7.0 core:cancel (a.stack-toggle)
  4x -0:16.3.0 core:backspace (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:12.5.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:10.4.0 core:backspace (atom-text-editor.editor.autocomplete-active.is-focused)
  3x -0:08.4.0 autocomplete-plus:cancel (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:06.0 core:cancel (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:04.4.0 core:move-up (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:04.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.autocomplete-active.is-focused)
  2x -0:03.8.0 core:backspace (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:03.1.0 markdown-writer:insert-new-line (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:03.1.0 editor:newline (atom-text-editor.editor.autocomplete-active.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "autoHideMenuBar": true,
    "disabledPackages": [
      "color-picker",
      "jekyll",
      "language-cmake",
      "pigments",
      "symbols-view"
    ],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "linter-gcc": {
    "execPath": "arm-none-eabi-gcc",
    "gccDebug": true,
    "gccIncludePaths": "./include",
    "gccLintOnTheFly": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.26
atom-ctags, v4.5.0
file-icons, v1.6.18
language-doxygen, v0.2.1
linter, v1.11.3
linter-gcc, v0.6.8
markdown-writer, v2.3.2
minimap, v4.20.0
wakatime, v5.0.8

# Dev
No dev packages
```

**Comment by hebaishi** [comment]
Hello. The issue is that you need to specify all the settings in your ```.gcc-flags.json``` file, even the ones that are the same as the configuration page. Specifying settings partially is not possible at the moment. I don't have access to a computer at the moment so I can't implement this feature straight away but I will be able to do it in about a week's time.

**Comment by edjubuh** [comment]
Perfect, that worked. Thanks!
