### ISSUE TITLE
"file" is read-only

### ISSUE THREAD

**Issue by guysherman** [hebaishi/linter-gcc#4]
SyntaxError: /home/guy/.atom/packages/linter-gcc/lib/main.js: Line 78: "file" is read-only
  76 |             editor = atom.workspace.getActivePaneItem();
  77 |             if (editor) {
> 78 |                 file = editor.buffer.file;
     |                 ^
  79 |                 if (file) {
  80 |                     cwd = file.getParent().getPath();
  81 |                 }
    at File.errorWithNode (/opt/atom/resources/app.asar/node_modules/babel-core/lib/babel/transformation/file/index.js:451:13)
    at checkPath (/opt/atom/resources/app.asar/node_modules/babel-core/lib/babel/transformation/transformers/es6/constants.js:33:16)
    at NodePath.AssignmentExpression (/opt/atom/resources/app.asar/node_modules/babel-core/lib/babel/transformation/transformers/es6/constants.js:38:3)
    at NodePath.call (/opt/atom/resources/app.asar/node_modules/babel-core/lib/babel/traversal/path/context.js:130:26)
    at NodePath.visit (/opt/atom/resources/app.asar/node_modules/babel-core/lib/babel/traversal/path/context.js:154:8)
    at TraversalContext.visitSingle (/opt/atom/resources/app.asar/node_modules/babel-core/lib/babel/traversal/context.js:92:12)
    at TraversalContext.visit (/opt/atom/resources/app.asar/node_modules/babel-core/lib/babel/traversal/context.js:104:19)
    at Function.traverse.node (/opt/atom/resources/app.asar/node_modules/babel-core/lib/babel/traversal/index.js:67:17)
    at NodePath.visit (/opt/atom/resources/app.asar/node_modules/babel-core/lib/babel/traversal/path/context.js:171:26)
    at TraversalContext.visitMultiple (/opt/atom/resources/app.asar/node_modules/babel-core/lib/babel/traversal/context.js:72:16)

**Comment by hebaishi** [comment]
The error suggests that this is a file permissions issue. Could you confirm that you have the permission to write to the file? Could you maybe paste the output of
```bash
ls -la /path/to/file
```

**Comment by guysherman** [comment]
Hi here's the listing for the file that is the active pane

guy@guy-linux:~/Code/panda/panda$ atom .
guy@guy-linux:~/Code/panda/panda$ ls -la src/panda-host/web_server.cxx 
-rw-rw-r-- 1 guy guy 7953 Aug 22 19:22 src/panda-host/web_server.cxx

And here are listings for the rest of the files:

guy@guy-linux:~/Code/panda/panda$ ls -la .
total 220
drwxrwxr-x 6 guy guy  4096 Aug 17 11:15 .
drwxrwxr-x 4 guy guy  4096 Aug 17 11:13 ..
-rw-rw-r-- 1 guy guy    56 Aug 16 22:03 .atom-build.json
drwxrwxr-x 4 guy guy  4096 Aug 22 19:22 build
drwxrwxr-x 8 guy guy  4096 Aug 22 00:09 .git
-rw-rw-r-- 1 guy guy   275 Aug 22 00:04 .gitignore
-rw-rw-r-- 1 guy guy 18047 Aug 17 11:13 LICENSE
-rw-rw-r-- 1 guy guy  4780 Aug 22 18:42 .lock-waf_linux2_build
-rw-rw-r-- 1 guy guy   212 Aug 21 21:44 README.md
drwxrwxr-x 4 guy guy  4096 Aug 21 21:48 src
-rwxr-xr-x 1 guy guy 97567 Jul  5 19:48 waf
drwxrwxr-x 3 guy guy  4096 Aug 17 11:15 .waf-1.8.12-f00e5b53f6bbeab1384a38c9cc5d51f7
-rw-rw-r-- 1 guy guy  1542 Aug 22 18:42 wscript

guy@guy-linux:~/Code/panda/panda$ ls -la src/panda-host/
total 48
drwxrwxr-x 2 guy guy 4096 Aug 21 22:12 .
drwxrwxr-x 4 guy guy 4096 Aug 21 21:48 ..
-rw-rw-r-- 1 guy guy 1780 Aug 22 18:23 main.cxx
-rw-rw-r-- 1 guy guy 7953 Aug 22 19:22 web_server.cxx
-rw-rw-r-- 1 guy guy 2486 Aug 22 18:49 web_server.hxx

guy@guy-linux:~/Code/panda/panda$ ls -la src/util
total 32
drwxrwxr-x 2 guy guy 4096 Aug 21 21:48 .
drwxrwxr-x 4 guy guy 4096 Aug 21 21:48 ..
-rw-rw-r-- 1 guy guy 3292 Aug 20 19:22 liblo-example.cxx
-rw-rw-r-- 1 guy guy 2154 Aug 16 19:50 panda-sim.cxx

As you can see there's nothing out of the ordinary with the file permissions: owner and group have rw, and others have r.

Note that this happens when I open atom.

Cheers,

Guy.

**Comment by guysherman** [comment]
Looking at the code I think the clue is probably at line 90 where file is defined:

const file = activeEditor.getPath();

if I move that line up to the top of the lint function, and change the const to a var, then it doesn't throw that error. However, I can't see that it is actually linting anything.

**Comment by guysherman** [comment]
Ok, so the lack of linting was because I didn't have linter installed. My bad. I went back and checked the initial issue with linter installed, and it still happened. Have sent you a PR.

**Comment by hebaishi** [comment]
Thanks for fixing it! Pull request accepted.
