### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by baillyjamy** [hebaishi/linter-gcc#52]
Hello, I have encountered the following exception:

**Atom Version**: 1.7.2
**System**: linux 4.5.1-1-ARCH
**Thrown From**: [linter-gcc](https://github.com/hebaishi/linter-gcc) package, v0.6.12

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:8

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:479:5)
    at /home/bailly_j/.atom/packages/linter-gcc/lib/utility.js:66:34
    at Array.forEach (native)
    at Object.module.exports.splitStringTrim (/home/bailly_j/.atom/packages/linter-gcc/lib/utility.js:62:14)
    at Object.module.exports.buildCommand (/home/bailly_j/.atom/packages/linter-gcc/lib/utility.js:132:40)
    at Object.lint (/home/bailly_j/.atom/packages/linter-gcc/lib/main.js:92:36)
    at lintOnTheFly (/home/bailly_j/.atom/packages/linter-gcc/lib/main.js:145:22)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1369:25
```

### Commands

```
     -0:07.5.0 grammar-selector:show (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-clang"
    ]
  },
  "linter-gcc": {
    "execPath": "gcc",
    "gccDebug": true,
    "gccDefaultCFlags": "-only -c -W -Wall -Wextra -pedantic -posix -o /dev/null",
    "gccIncludePaths": "./include",
    "gccLintOnTheFly": true
  }
}
```

### Installed Packages

```coffee
# User
epitech-headers, v0.2.8
epitech-norm-linter, v1.10.0
linter, v1.11.4
linter-gcc, v0.6.12

# Dev
No dev packages
```

**Comment by hebaishi** [comment]
I have identified the problem and will publish a fix very shortly. Thank you for reporting the error.

**Comment by hebaishi** [comment]
Ok. The fix has been made. Please update linter-gcc. Note that you need to restart atom (`Ctrl+Alt+R`) to reload the package. Please let me know once you have it working again.

**Comment by baillyjamy** [comment]
Sorry but linter-gcc does not work. Yet I haven't more error message.

**Comment by hebaishi** [comment]
Just to clarify - does this occur only with an unsaved file or with saved ones as well?

**Comment by baillyjamy** [comment]
This occur for both cases

**Comment by hebaishi** [comment]
Could you follow the instructions [here](https://github.com/hebaishi/linter-gcc/wiki/Common-Issues) and report the linter-gcc command that appears in the developer console?

**Comment by hebaishi** [comment]
Hello? Any update on your problem?

**Comment by baillyjamy** [comment]
I will do that this evening :)

**Comment by baillyjamy** [comment]
Sorry for the delay

```
/home/bailly_j/.atom/packages/linter-gcc/lib/utility.js:94 
linter-gcc config: 
{"execPath":"gcc","gccIncludePaths":"./include","gccSuppressWarnings":false,"gccDefaultCFlags":"-only -c -W -Wall -Wextra -pedantic -posix -o /dev/null","gccDefaultCppFlags":"-c -Wall -std=c++11","gccErrorLimit":0,"gccErrorString":"error","gccWarningString":"warning","gccNoteString":"note"}
```

```
/home/bailly_j/.atom/packages/linter-gcc/lib/utility.js:146 
linter-gcc: 
/usr/lib/hardening-wrapper/bin/gcc -only -c -W -Wall -Wextra -pedantic -posix -o /dev/null -fmax-errors=0 -I/home/bailly_j/rendu/Dante/include /tmp/2f6adb7c-eb69-431d-b77b-d0d54c414a79.c
```

**Comment by hebaishi** [comment]
One little thing - could you turn off linting on-the-fly, then take the command that linter-gcc prints in the console, and paste it into a terminal? We need to see the command output to work out what the problem is.

**Comment by baillyjamy** [comment]
Well the problem was with my operating system. I fixed a problem with my pipes and the bug disappeared. I do not know if it's related but I do not have the bug

**Comment by riophae** [comment]
[Enter steps to reproduce:]

1. Hit Ctrl-N to create a new empty file without saving it.
2. Paste some C code and change the language setting to C.
3. linter-gcc starts to work but throws this error.

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [linter-gcc](https://github.com/hebaishi/linter-gcc) package 0.7.1


### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:466:7)
    at /packages/linter-gcc/lib/utility.js:105:24
    at Array.forEach (native)
    at Object.splitStringTrim (/packages/linter-gcc/lib/utility.js:97:14)
    at Object.buildCommand (/packages/linter-gcc/lib/utility.js:197:42)
    at Object.lint (/packages/linter-gcc/lib/main.js:110:36)
    at /packages/linter-gcc/lib/main.js:180:26
```

### Commands

```
     -2:08.8.0 atom-beautify:beautify-editor (div.line)
     -2:05.5.0 intentions:highlight (input.hidden-input)
     -2:05.4.0 core:select-all (input.hidden-input)
     -2:05.3.0 core:copy (input.hidden-input)
     -1:39.3.0 intentions:highlight (input.hidden-input)
     -1:39.2.0 core:select-all (input.hidden-input)
     -1:38.8.0 core:copy (input.hidden-input)
     -1:38.8.0 core:paste (input.hidden-input)
     -1:27.3.0 intentions:highlight (input.hidden-input)
     -1:27.2.0 core:select-all (input.hidden-input)
     -1:26.7.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.29.17 
atom-typescript 10.1.15 
atomic-chrome 0.3.0 
busy-signal 1.3.0 
duotone-light-syntax 2.1.0 
editorconfig 2.2.2 
emmet 2.4.3 
eslint-fixer 1.2.1 
ficus-syntax 2.0.0 
flatwhite-syntax 0.8.0 
fonts 2.0.0 
gl-light-syntax 2.2.0 
intentions 1.1.2 
language-babel 2.56.2 
language-cuesheet 0.1.5 
linter 2.1.0 
linter-eslint 8.1.4 
linter-gcc 0.7.1 
linter-tslint 0.14.0 
linter-ui-default 1.2.0 
linter-write-good 0.8.0 
northem-light-atom-syntax 2.1.0 
northem-light-atom-ui 2.1.0 
script 3.14.1 
spacegray-light-neue-ui 0.1.7 
sync-settings 0.8.1 
zentabs 0.8.8 
```
