### ISSUE TITLE
Uncaught TypeError with gcc-flags.json

### ISSUE THREAD

**Issue by nexhub** [hebaishi/linter-gcc#53]
EDIT:
The error occurs with on-the-fly-linting disabled, too.
I also included another Stacktrace.
___
Hi,
I got a problem with on the fly linting and gcc-flags.json. I don't really know, if it depends ony my setup. But think it's not that exotic, so I decided to post in here.
If I don't use gccIncludePaths, obviously gcc can not find my header files: "RunMgr.hpp no such file or directory".
my setup: .gcc-flags.json in project directory, sourcefiles in .src/
```
./gcc-flags.json
./src/runMgr.cpp
./src/runMgr.hpp
```

with the following .json file, the first error is gone, but a big red atom "Uncaugt TypeError" pops up.
```
{
    "gccIncludePaths": "./src"
}
```
I hope you/I can help you/me :)

**GCC version**: 4.9.2
**Atom Version**: 1.7.3
**System**: Ubuntu 15.04
**Thrown From**: [linter-gcc](https://github.com/hebaishi/linter-gcc) package, v0.6.14

### Stack Trace

Uncaught TypeError: Cannot read property 'substring' of undefined

```
At /home/s5800160/.atom/packages/linter-gcc/lib/utility.js:101

TypeError: Cannot read property 'substring' of undefined
    at Object.module.exports.buildCommand (/home/s5800160/.atom/packages/linter-gcc/lib/utility.js:101:16)
    at Object.lint (/home/s5800160/.atom/packages/linter-gcc/lib/main.js:93:36)
    at lintOnTheFly (/home/s5800160/.atom/packages/linter-gcc/lib/main.js:146:22)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1378:25
```

### Commands

```
     -0:09.3.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:07.1.0 window:toggle-dev-tools (atom-text-editor.editor.is-focused)
     -0:03.3.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "build",
      "activate-power-mode",
      "atom-beautify",
      "gpp-compiler"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "linter-gcc": {
    "gccDebug": true,
    "gccDefaultCFlags": "-Wall",
    "gccDefaultCppFlags": "-std=c  11 -Wall",
    "gccLintOnTheFly": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-clang, v0.9.3
counter, v0.3.3
language-doxygen, v0.2.1
linter, v1.11.4
linter-clang, v3.4.4
linter-cppcheck, v0.2.0
linter-gcc, v0.6.14

# Dev
No dev packages
```
___
### Stacktrace # 2

**Atom Version**: 1.7.3
**System**: Ubuntu 15.04
**Thrown From**: [linter-gcc](https://github.com/hebaishi/linter-gcc) package, v0.6.14

### Stack Trace

Uncaught TypeError: Cannot read property 'substring' of undefined

```
At /usr/share/atom/resources/app.asar/src/pane.js:1002

TypeError: Cannot read property 'substring' of undefined
    at Object.module.exports.buildCommand (/home/s5800160/.atom/packages/linter-gcc/lib/utility.js:101:16)
    at Object.lint (/home/s5800160/.atom/packages/linter-gcc/lib/main.js:93:36)
    at lintOnSave (/home/s5800160/.atom/packages/linter-gcc/lib/main.js:154:22)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1113:27)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/usr/share/atom/resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:27.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:26.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:24.3.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:23.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "build",
      "activate-power-mode",
      "atom-beautify",
      "gpp-compiler"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "linter-gcc": {
    "gccDebug": true,
    "gccDefaultCFlags": "-Wall",
    "gccDefaultCppFlags": "-std=c++11 -Wall"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-clang, v0.9.3
counter, v0.3.3
language-doxygen, v0.2.1
linter, v1.11.4
linter-clang, v3.4.4
linter-cppcheck, v0.2.0
linter-gcc, v0.6.14

# Dev
No dev packages
```

**Comment by hebaishi** [comment]
The issue is that you are not specifying all the options in your `.gcc-flags.json` file. Please use the example in the [README](https://github.com/hebaishi/linter-gcc) as a template. Mixing options between the configuration page and the `.gcc-flags.json` file is not currently supported, but I have it on my todo list. Please let me know when you've got it working.

**Comment by nexhub** [comment]
Ok, that makes sense. Perhaps one should note that in the readme.
I deleted all options in my package configuration and used solely the.gcc-flags.json .
Now "RunMgr.hpp: No such file or directory" is back again.

{
  "execPath": "/usr/bin/g++",
  "gccDefaultCFlags": "-Wall",
  "gccDefaultCppFlags": "-Wall -std=c++11",
  "gccErrorLimit": 15,
  "gccIncludePaths": "./src",
  "gccSuppressWarnings": false
}

**Comment by hebaishi** [comment]
Yep. Will add a note in the README. Thanks for bringing it up.

**Comment by nexhub** [comment]
Didn't I specify all options like mentioned in the README?

![lint-gcc](https://cloud.githubusercontent.com/assets/9883380/15110698/beac92ea-15e2-11e6-817f-5218437f72f8.png)

**Comment by hebaishi** [comment]
Yes you did - just wanted to say that you don't need to delete the options on the configuration page.

**Comment by nexhub** [comment]
Sorry, I didn't explain myself. Look at the error, it's still there.
Seems to me like, the include path option is not working. Before when the file wasn't complete it worked, iirc.

**Comment by hebaishi** [comment]
I think the issue is that you have two github repos open. linter-gcc uses the project root to expand the include directory path. Close all your projects except the one you are using, and try it again.

**Comment by nexhub** [comment]
now it's working, thank you very much!
