### ISSUE TITLE
Uncaught SyntaxError: /home/hgst/dev/mp/.gcc-flags.json: Unexpected string

### ISSUE THREAD

**Issue by esteinert** [hebaishi/linter-gcc#54]
[Enter steps to reproduce below:]

1. Made change in file
2. Attempted to save file

**Atom Version**: 1.7.3
**System**: Debian GNU/Linux
**Thrown From**: [linter-gcc](https://github.com/hebaishi/linter-gcc) package, v0.6.14

### Stack Trace

Uncaught SyntaxError: /home/hgst/dev/mp/.gcc-flags.json: Unexpected string

```
At /usr/share/atom/resources/app.asar/src/pane.js:1002

SyntaxError: /home/hgst/dev/mp/.gcc-flags.json: Unexpected string
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:440:27)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.settings (/home/hgst/.atom/packages/linter-gcc/lib/config.js:49:25)
    at Object.module.exports.buildCommand (/home/hgst/.atom/packages/linter-gcc/lib/utility.js:91:23)
    at Object.lint (/home/hgst/.atom/packages/linter-gcc/lib/main.js:93:36)
    at lintOnSave (/home/hgst/.atom/packages/linter-gcc/lib/main.js:154:22)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1113:27)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/usr/share/atom/resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:23.8.0 core:copy (atom-text-editor.editor.is-focused)
     -0:11.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:10.6.0 core:paste (atom-text-editor.editor.is-focused)
     -0:05.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:04.9.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:04.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:04.9.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:00.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "autocomplete-ctags",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-php",
      "language-perl",
      "language-objective-c",
      "language-mustache",
      "language-javascript",
      "language-java",
      "language-toml",
      "language-yaml",
      "open-on-github",
      "atom-rtags",
      "atomic-rtags",
      "symbols-view",
      "epitools"
    ]
  },
  "linter-gcc": {
    "execPath": "/usr/bin/gcc",
    "gccDefaultCFlags": "-c -Wall -fsyntax-only",
    "gccDefaultCppFlags": "-c -Wall -fsyntax-only"
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v4.5.2
linter, v1.11.4
linter-gcc, v0.6.14
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by esteinert** [comment]
I'm am idiot and can't json properly. Forgot a comma.
