### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir '/home/local/DOMAIN2003/test50/git/inc...

### ISSUE THREAD

**Issue by y12345e** [hebaishi/linter-gcc#55]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0-beta3
**System**: Ubuntu 12.04.4
**Thrown From**: [linter-gcc](https://github.com/hebaishi/linter-gcc) package, v0.6.14

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir '/home/local/DOMAIN2003/test50/git/include -I/usr/include/libxml2'

```
At /usr/local/share/atom-beta/resources/app.asar/src/pane.js:1002

Error: ENOENT: no such file or directory, scandir '/home/local/DOMAIN2003/test50/git/include -I/usr/include/libxml2'
    at Error (native)
    at Object.fs.readdirSync (fs.js:856:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:497:28)
    at Object.module.exports.walkSync (/home/local/DOMAIN2003/test50/.atom/packages/linter-gcc/lib/utility.js:15:16)
    at /home/local/DOMAIN2003/test50/.atom/packages/linter-gcc/lib/utility.js:75:37
    at Array.forEach (native)
    at Object.module.exports.splitStringTrim (/home/local/DOMAIN2003/test50/.atom/packages/linter-gcc/lib/utility.js:66:14)
    at Object.module.exports.buildCommand (/home/local/DOMAIN2003/test50/.atom/packages/linter-gcc/lib/utility.js:136:40)
    at Object.lint (/home/local/DOMAIN2003/test50/.atom/packages/linter-gcc/lib/main.js:93:36)
    at lintOnSave (/home/local/DOMAIN2003/test50/.atom/packages/linter-gcc/lib/main.js:154:22)
    at Function.module.exports.Emitter.simpleDispatch (/usr/local/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/local/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/local/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1113:27)
    at TextBuffer.module.exports.TextBuffer.save (/usr/local/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/usr/local/share/atom-beta/resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/usr/local/share/atom-beta/resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/usr/local/share/atom-beta/resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/local/share/atom-beta/resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/usr/local/share/atom-beta/resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/local/share/atom-beta/resources/app.asar/src/command-registry.js:260:29)
    at /usr/local/share/atom-beta/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/local/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/local/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/local/share/atom-beta/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/local/share/atom-beta/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:00.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode",
      "activate-power-mode"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "linter-gcc": {
    "gccIncludePaths": ".,../,./include,../include -I/usr/include/libxml2/*"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.7
atom-material-syntax, v0.4.6
atom-material-ui, v1.2.11
autocomplete-paths, v1.0.2
docblockr, v0.7.3
emmet, v2.4.3
esformatter, v1.25.0
file-icons, v1.7.11
highlight-selected, v0.11.2
linter, v1.11.4
linter-gcc, v0.6.14
merge-conflicts, v1.4.2
minimap, v4.23.5
minimap-bookmarks, v0.3.1
minimap-find-and-replace, v4.5.1
minimap-highlight-selected, v4.4.0
minimap-selection, v4.4.0
pigments, v0.26.2
simplified-chinese-menu, v3.4.11
sync-settings, v0.7.2
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by hebaishi** [comment]
Your `gccIncludePaths` is incorrect. You must supply a list of paths, separated by commas. You have `-I` in your list of paths, which is incorrect.

**Comment by hebaishi** [comment]
Has your issue been resolved?

**Comment by y12345e** [comment]
yes
